---

resource-types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources: 
- name: platform-automation
  type: pivnet
  source: 
    product-slug: platform-automation
    api-token: ((pivnet-refresh-token))
- name: config
  type: git
  source: 
    uri: ((pipeline-repo))
    privat-key: ((plat-auto-pipes-deploy-key.privat_key))
    branch: master

jobs:
- name: install-ops-manager
  serial: true
  plan:
    - get: platform-automation-image
      resource: platform-automation-image
      params:
        globs: ["*image*.tgz"]
        unpack: true
    - get: platform-automation-tasks
      resource: platform-automation
      params: 
        globs: ["*tasks*.zip"]
        unpack: true
    - get: config
    - task: credhub-interpolate
      image: platform-automation-image
      file: platform-automation-tasks/tasks/credhub-interpolate.yml
      params:
        CREDHUB_CLIENT: ((credhub-client))
        CREDHUB_SECRET: ((credhub-secret))
        CREDHUB_SERVER: https://your-credhub-example.com
        PREFIX: /concourse/your-team-name-foundation
      input_mapping: 
        files: config
      output_mapping: 
        interpolated-files: interpolated-config
    - task: download-product
      image: platform-automation-image
      file: platform-automation-tasks/tasks/download-product.yml
      params: 
        CONFG_FILE: download-ops-manager.yml
      input_mapping: 
        config: interpolated-config
    - task: create-vm
      image: platform-automation-image
      file: platform-automation-tasks/tasks/create-vm.yml
      
